{% set name = "pyimagej" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8774772b5d5c8189e8ba6a217713f10ff3a5815e7005ee0933822f52650243d0

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vvv  --no-deps"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyjnius
    - imglyb
    - matplotlib-base
    - numpy
    - xarray
    - pillow
    - scyjava
    - requests

test:
  imports:
    - imagej

about:
  home: https://github.com/imagej/pyimagej
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'The Python wrapper for ImageJ.'
  doc_url: https://github.com/imagej/pyimagej
  dev_url: https://github.com/imagej/pyimagej

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
