{% set name = "pyimagej" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 720dc1d1d7e95fff49d78106a84bd185ea5a341716c7dfc9f9b2cc131a92bbd0

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vvv  --no-deps
  skip: true  # [py2k or (py>38 and win)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - imglyb >=2.0.1
    - jgo >=1.0.3
    - jpype1 >=1.3.0
    - labeling >=0.1.12
    - matplotlib-base
    - numpy
    - scyjava >=1.8.0
    - xarray

test:
  imports:
    - imagej

about:
  home: https://github.com/imagej/pyimagej
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: The Python wrapper for ImageJ.
  doc_url: https://github.com/imagej/pyimagej
  dev_url: https://github.com/imagej/pyimagej

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
