{% set name = "pyimagej" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75e4f9ea8ebdbfb8ea00ff160d857ef62f99318caf558afbe2d907ab605b6ec9

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vvv  --no-deps
  skip: true  # [py2k or (py>38 and win)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - imglyb >=2.0.1
    - jgo >=1.0.3
    - jpype1 >=1.3.0
    - labeling >=0.1.12
    - matplotlib-base
    - numpy
    - scyjava >=1.8.0
    - xarray

test:
  imports:
    - imagej

about:
  home: https://github.com/imagej/pyimagej
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: The Python wrapper for ImageJ.
  doc_url: https://github.com/imagej/pyimagej
  dev_url: https://github.com/imagej/pyimagej

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - hinerm
