appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: iJn74fhEK4udVXlgIaA5OCjunQ3UAg8gKLcAfCoVr/6cHjYYBNAI/xvU8ylumBYbcEBpBLkcT+nBZofum08w4SB47tLCxKIYdS6cTOV1bvlDUMOWPdTDIOvr6mJWrGv+rkJd14uJfzyCnEHQpX5lAve+dRPxz2cB7kswRBXRrpQ85woF7BJvNJ8oXbpVRo8VC3olONcpNfWA29WGd+CyO1FRVn12zUgLunDjkz/qNUzUg8WcyN76sC4hHTG70hJcsax7tBCEu4ML84aWoSWCyISi+Ruxw/HxTUQQhONUbr5fCJan8I57bMJnRojaU4aFQXS5Ya4WW/hCLDhooeLwMgrk9Y35IoAU/xmwDcZUB5hoi6uAVw3FiVMXMm5GKP7y66ifosocGM/Au6A/oG1sjobvvInvkHbm+eTGXs1HTTzV/syHD6i+PWJn1lpN8wYxyRNYK0W3nPw/TxlgEqwav8d2tYxGwmE/bvcEYP9XdWR1KLtPHBJCof8qJzo+/Psis0Wy7cG8y1f08LMwmFnU86R6fuAoaOif9aPuGud59nD2IWh50QWrA85yf66fNPWfyreFcuFzFqgj6WPbAoya6xoDU+R65DUCfMUqETRyNdn0YOS9AqlyMBKnSoP67/pnrVCnEkay6d9TQL+bikGTUzmW0NjlXPCSppJ5lhLqCKE=}
conda_forge_output_validation: true
